version: "3.8"

services:
  database:
    container_name: db
    image: postgres:14.2
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

  backend:
    container_name: api
    build:
      dockerfile: Dockerfile
      context: .
    restart: on-failure
    depends_on:
      - database
    ports:
      - "3000:3000"
    environment:
      - DATABASE_HOST=database
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=maryam
      - DATABASE_NAME=postgres
      - DATABASE_SYNCHRONIZE=true
      - GRAPHQL_PLAYGROUND_ENABLED=true
      - NODE_ENV=production
